version : "3.9"
services :
  proyectos-desacoplados : 
    container_name : proyectos-desacoplados
    image : proyectos-desacoplados:v1
    env_file:
      - .env    
    build :
      context : .
    ports : 
      - "4003"
    networks : 
      - proyectos-app


  proyectos-desacoplados2 : 
    container_name : proyectos-desacoplados2
    image : proyectos-desacoplados:v1
    env_file:
      - .env    
    ports : 
      - "4003"
    networks : 
      - proyectos-app


  balanceador : 
    container_name : balanceador
    image : balanceador:v1
    env_file:
      - .env    
    build :
      context : ./balanceador
    ports : 
      - "4004:80"
    networks : 
      - proyectos-app


networks : 
  proyectos-app :